events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    server {
        listen 10000;
        location / {
            root /tmp;
            add_header Access-Control-Allow-Origin *;
            add_header Cache-Control no-cache;
        }
    }
}